[versions]
junit-jupiter = "5.10.3"
spring-boot = "3.2.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-systemExit = { module = "com.ginsberg:junit5-system-exit", version = "2.0.2" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.12" }
airline = { module = "com.github.rvesse:airline", version = "3.0.0" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
